### ISSUE TITLE
请问应该打开的是localhost的哪个端口号?

### ISSUE THREAD

**Issue by njusmx** [lazyhero/vue-spa-demo#4]
请问应该打开的是localhost的哪个端口号?

**Comment by masiqi** [comment]
npm run dev 会显示，一般是8080

**Comment by lazyhero** [comment]
抱歉抱歉才看到～ 满屏的其它issue 导致没看到这个……
为了弥补……
端口号一般会在目录下的config.js，build.js 等配置文件中
再有就是推荐一款工具
![image](https://cloud.githubusercontent.com/assets/9362926/16401919/fe670b18-3d1a-11e6-8060-6f24f9d7d307.png)
它可以帮助你在当前目录下切到终端 
结合 anywhere这款插件 可以启动一个小的web容器～让你可以跑些轻量的页面项目；
